name: seav_phov
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages
publish_to: "none"

# https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

# `flutter pub upgrade --major-versions`
# `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  responsive_builder: ^0.4.3
  kdgaugeview: ^1.0.4
  cloud_firestore: ^4.3.1
  firebase_core: ^2.3.0
  url_launcher: ^6.1.8
  scroll_to_index: ^3.0.1
  rect_getter: ^1.1.0
  blur_container: ^0.0.2
  add_to_cart_animation: ^2.0.3
  splash_route: ^0.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^2.2.0
  page_transition: ^2.0.9
  adaptive_dialog: ^1.8.2
  modal_bottom_sheet: ^2.1.2
  dialogs: ^0.0.7
  commons: ^0.2.3
  multi_select_flutter: ^4.1.3
  awesome_select: ^6.0.0
  select_dialog: ^2.0.0
  item_selector: ^0.2.0
  custom_radio_grouped_button: ^2.1.2+2
  custom_radio_group_list: ^1.0.0
  flutter_native_splash: ^2.2.18
  sliver_tools: ^0.2.5
  dropdown_button2: ^2.0.0
  flutter_slidable: ^1.2.0
  material_design_icons_flutter: ^6.0.7096
  timeago: ^3.3.0
  tuple: ^2.0.1
  radio_group_v2: ^1.0.2
  cached_network_image: ^3.2.3
  vimeo_video_player: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/


  # https://flutter.dev/assets-and-images/#resolution-aware
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
